version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: userpass123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: tauseefkhorajia/ecommerce-app-two-tier:latest
    container_name: ecommerce-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: ecommerce_user
      DB_PASSWORD: userpass123
      DB_NAME: ecommerce_db
      PORT: 5000
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  mysql-data:
