apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: ecommerce
  annotations:
    # Use nginx ingress controller
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # Specify ingress class
  ingressClassName: nginx
  
  # Rules for routing traffic
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ecommerce-service
            port:
              number: 80
