apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ecommerce
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "RootPass@2025"
  MYSQL_DATABASE: "ecommerce_db"
  MYSQL_USER: "ecommerce_user"
  MYSQL_PASSWORD: "EcomPass@2025"
